set( SOFTART_LLVM_TEST_CASE_HEADERS "" )
set( SOFTART_LLVM_TEST_CASE_SOURCES	"" )

if( SOFTART_BUILD_WITH_LLVM )
	set( SOFTART_LLVM_TEST_CASE_HEADERS cgllvm_cases.h )
	set( SOFTART_LLVM_TEST_CASE_SOURCES	cgllvm_cases.cpp )
endif( SOFTART_BUILD_WITH_LLVM )