set( SALVIA_AUTO_TEST_HOME "${SASL_HOME_DIR}/sasl/test/auto_test/repo" )

set( TEST_SHADER_CODES
	"${SALVIA_AUTO_TEST_HOME}/array.svs"
	"${SALVIA_AUTO_TEST_HOME}/array_and_index.ss"
	"${SALVIA_AUTO_TEST_HOME}/assigns.ss"
	"${SALVIA_AUTO_TEST_HOME}/comments.ss"
	"${SALVIA_AUTO_TEST_HOME}/constructors.ss"
	"${SALVIA_AUTO_TEST_HOME}/constructors.sps"
	"${SALVIA_AUTO_TEST_HOME}/ddx_ddy.sps"
	"${SALVIA_AUTO_TEST_HOME}/decl.ss"
	"${SALVIA_AUTO_TEST_HOME}/deps.ss"
	"${SALVIA_AUTO_TEST_HOME}/null.ss"
	"${SALVIA_AUTO_TEST_HOME}/preprocessors.ss"
	"${SALVIA_AUTO_TEST_HOME}/semantic.svs"
	"${SALVIA_AUTO_TEST_HOME}/semantic_fn.svs"
	"${SALVIA_AUTO_TEST_HOME}/semfn_par.svs"
	"${SALVIA_AUTO_TEST_HOME}/struct_semin.svs"
	"${SALVIA_AUTO_TEST_HOME}/vec_and_mat.svs"
	"${SALVIA_AUTO_TEST_HOME}/vec_and_mat.sps"
	"${SALVIA_AUTO_TEST_HOME}/arithmetic.ss"
	"${SALVIA_AUTO_TEST_HOME}/arithmetic.sps"
	"${SALVIA_AUTO_TEST_HOME}/function.ss"
	"${SALVIA_AUTO_TEST_HOME}/input_assigned.svs"
	"${SALVIA_AUTO_TEST_HOME}/intrinsics.ss"
	"${SALVIA_AUTO_TEST_HOME}/intrinsics.svs"
	"${SALVIA_AUTO_TEST_HOME}/intrinsics.sps"
	"${SALVIA_AUTO_TEST_HOME}/branches.ss"
	"${SALVIA_AUTO_TEST_HOME}/branches.sps"
	"${SALVIA_AUTO_TEST_HOME}/empty.ss"
	"${SALVIA_AUTO_TEST_HOME}/bool.ss"
	"${SALVIA_AUTO_TEST_HOME}/unary_operators.ss"
	"${SALVIA_AUTO_TEST_HOME}/host_intrinsic_detection.ss"
	"${SALVIA_AUTO_TEST_HOME}/initializer.ss"
	"${SALVIA_AUTO_TEST_HOME}/casts.ss"
	"${SALVIA_AUTO_TEST_HOME}/scalar.sps"
	"${SALVIA_AUTO_TEST_HOME}/swizzle.ss"
	"${SALVIA_AUTO_TEST_HOME}/swizzle_and_wm.sps"
	"${SALVIA_AUTO_TEST_HOME}/tex.svs"
	"${SALVIA_AUTO_TEST_HOME}/tex.sps"
	"${SALVIA_AUTO_TEST_HOME}/for_loop.sps"
	"${SALVIA_AUTO_TEST_HOME}/while.sps"
	"${SALVIA_AUTO_TEST_HOME}/do_while.sps"
	"${SALVIA_AUTO_TEST_HOME}/local_var.ss"
	"${SALVIA_AUTO_TEST_HOME}/bit_ops.ss"
	
	"${SALVIA_AUTO_TEST_HOME}/include_header.ss"
	"${SALVIA_AUTO_TEST_HOME}/include_main.ss"
	"${SALVIA_AUTO_TEST_HOME}/include_search_path.ss"
	"${SALVIA_AUTO_TEST_HOME}/incomplete.ss"
	"${SALVIA_AUTO_TEST_HOME}/semantic_errors.ss"
	
	"${SALVIA_AUTO_TEST_HOME}/include/header.ss"
	"${SALVIA_AUTO_TEST_HOME}/sysincl/sysheader.ss"
)

SOURCE_GROUP( "Tests\\General" REGULAR_EXPRESSION ".*\\.ss" )
SOURCE_GROUP( "Tests\\Vertex Shaders" REGULAR_EXPRESSION ".*\\.svs" )
SOURCE_GROUP( "Tests\\Pixel Shaders" REGULAR_EXPRESSION ".*\\.sps" )