#include <sasl/include/syntax_tree/declaration.h>
#include <sasl/include/code_generator/llvm/llvm_generator.h>
#include <llvm/DerivedTypes.h>
#include <llvm/Function.h>
#include <llvm/LLVMContext.h>
#include <llvm/Module.h>
#include <boost/shared_ptr.hpp>
#include <string>
#include <vector>
