set( SASL_ROBUST_TEST_HEADERS "" )
set( SASL_ROBUST_TEST_SOURCES "" )
set( SASL_ROBUST_TEST_LIBS "" )

set( SASL_ROBUST_TEST_HEADERS )
set( SASL_ROBUST_TEST_SOURCES
	${SASL_HOME_DIR}/sasl/test/robust_test/robust.cpp
)
set( SASL_ROBUST_TEST_LIBS
	${SASL_LLVM_LIBS}
)

if ( WIN32 AND MINGW )
	set ( SASL_ROBUST_TEST_LIBS imagehlp psapi )
endif( WIN32 AND MINGW )

ADD_DEFINITIONS(
	-DSASL_USE_LLVM
	-DSALVIA_USE_LLVM
)
