#define INITGUID
#include "common.h"

HRESULT APIENTRY OpenAdapter10(D3D10DDIARG_OPENADAPTER* pOpenData)
{
    UNREFERENCED_PARAMETER(pOpenData);
    return STATUS_NOT_IMPLEMENTED;
}

HRESULT APIENTRY OpenAdapter10_2(D3D10DDIARG_OPENADAPTER* pOpenData)
{
    UNREFERENCED_PARAMETER(pOpenData);
    return STATUS_NOT_IMPLEMENTED;
}
