#define INITGUID
#include "common.h"

NTSTATUS APIENTRY D3DKMTCreateAllocation(D3DKMT_CREATEALLOCATION* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTQueryResourceInfo(D3DKMT_QUERYRESOURCEINFO* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTOpenResource(D3DKMT_OPENRESOURCE* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTDestroyAllocation(const D3DKMT_DESTROYALLOCATION* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTSetAllocationPriority(const D3DKMT_SETALLOCATIONPRIORITY* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTQueryAllocationResidency(const D3DKMT_QUERYALLOCATIONRESIDENCY* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTCreateDevice(D3DKMT_CREATEDEVICE* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTDestroyDevice(const D3DKMT_DESTROYDEVICE* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTLock(D3DKMT_LOCK* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTUnlock(const D3DKMT_UNLOCK* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTGetDisplayModeList(D3DKMT_GETDISPLAYMODELIST* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTSetDisplayMode(const D3DKMT_SETDISPLAYMODE* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTGetMultisampleMethodList(D3DKMT_GETMULTISAMPLEMETHODLIST* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTPresent(const D3DKMT_PRESENT* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTRender(D3DKMT_RENDER* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTGetRuntimeData(const D3DKMT_GETRUNTIMEDATA* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTQueryAdapterInfo(const D3DKMT_QUERYADAPTERINFO* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTOpenAdapterFromGdiDisplayName(D3DKMT_OPENADAPTERFROMGDIDISPLAYNAME* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTOpenAdapterFromDeviceName(D3DKMT_OPENADAPTERFROMDEVICENAME* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTCloseAdapter(const D3DKMT_CLOSEADAPTER* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTGetSharedPrimaryHandle(D3DKMT_GETSHAREDPRIMARYHANDLE* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTEscape(const D3DKMT_ESCAPE* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTSetVidPnSourceOwner(const D3DKMT_SETVIDPNSOURCEOWNER* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}


NTSTATUS APIENTRY D3DKMTWaitForVerticalBlankEvent(const D3DKMT_WAITFORVERTICALBLANKEVENT* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTSetGammaRamp(const D3DKMT_SETGAMMARAMP* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTGetDeviceState(D3DKMT_GETDEVICESTATE* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTSetContextSchedulingPriority(const D3DKMT_SETCONTEXTSCHEDULINGPRIORITY* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTGetContextSchedulingPriority(D3DKMT_GETCONTEXTSCHEDULINGPRIORITY* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTCreateContext(D3DKMT_CREATECONTEXT* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTDestroyContext(const D3DKMT_DESTROYCONTEXT* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTCreateSynchronizationObject(D3DKMT_CREATESYNCHRONIZATIONOBJECT* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTDestroySynchronizationObject(const D3DKMT_DESTROYSYNCHRONIZATIONOBJECT* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTWaitForSynchronizationObject(const D3DKMT_WAITFORSYNCHRONIZATIONOBJECT* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTSignalSynchronizationObject(const D3DKMT_SIGNALSYNCHRONIZATIONOBJECT* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTSetDisplayPrivateDriverFormat(const D3DKMT_SETDISPLAYPRIVATEDRIVERFORMAT* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTSignalSynchronizationObject2(const D3DKMT_SIGNALSYNCHRONIZATIONOBJECT2* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTWaitForSynchronizationObject2(const D3DKMT_WAITFORSYNCHRONIZATIONOBJECT2* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTOpenSynchronizationObject(D3DKMT_OPENSYNCHRONIZATIONOBJECT* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTCreateSynchronizationObject2(D3DKMT_CREATESYNCHRONIZATIONOBJECT2* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTReleaseKeyedMutex(D3DKMT_RELEASEKEYEDMUTEX* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTAcquireKeyedMutex(D3DKMT_ACQUIREKEYEDMUTEX* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTDestroyKeyedMutex(const D3DKMT_DESTROYKEYEDMUTEX* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTOpenKeyedMutex(D3DKMT_OPENKEYEDMUTEX* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTCreateKeyedMutex(D3DKMT_CREATEKEYEDMUTEX* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTOpenResource2(D3DKMT_OPENRESOURCE* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTCreateAllocation2(D3DKMT_CREATEALLOCATION* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS APIENTRY D3DKMTConfigureSharedResource(const D3DKMT_CONFIGURESHAREDRESOURCE* pData)
{
	UNREFERENCED_PARAMETER(pData);
	return STATUS_NOT_IMPLEMENTED;
}
