/**************************
NEVER CHANGE THIS FILE MANUALLY!

This File Was Generated By enums_gen.py Automatically.
************************/

#include "../../include/enums/address_mode.h"

#include "eflib/include/eflib.h"

#ifdef _DEBUG
std::set<int>& address_mode::get_address_mode_table()
{
	static std::set<int> ret;
	return ret;
}
#endif

address_mode::address_mode(int v):val(v)
{
#ifdef _DEBUG
	if(get_address_mode_table().find(v) != get_address_mode_table().end()) {
		custom_assert(false, "");
	} else {
		get_address_mode_table().insert(v);
	}
#endif
}

address_mode address_mode::cast(int val)
{
	#ifdef _DEBUG
	if(get_address_mode_table().find(val) == get_address_mode_table().end()){
		custom_assert(false, "");
		return address_mode(0);
	}
	#endif
	return address_mode(val);
}

const address_mode address_mode::invalid(-1);
const address_mode address_mode::wrap(0);
const address_mode address_mode::mirror(1);
const address_mode address_mode::clamp(2);
const address_mode address_mode::border(3);
const address_mode address_mode::max(4);
