/**************************
NEVER CHANGE THIS FILE MANUALLY!

This File Was Generated By enums_gen.py Automatically.
************************/

#include "../../include/enums/cull_mode.h"

#include "eflib/include/eflib.h"

#ifdef _DEBUG
std::set<int>& cull_mode::get_cull_mode_table()
{
	static std::set<int> ret;
	return ret;
}
#endif

cull_mode::cull_mode(int v):val(v)
{
#ifdef _DEBUG
	if(get_cull_mode_table().find(v) != get_cull_mode_table().end()) {
		custom_assert(false, "");
	} else {
		get_cull_mode_table().insert(v);
	}
#endif
}

cull_mode cull_mode::cast(int val)
{
	#ifdef _DEBUG
	if(get_cull_mode_table().find(val) == get_cull_mode_table().end()){
		custom_assert(false, "");
		return cull_mode(0);
	}
	#endif
	return cull_mode(val);
}

const cull_mode cull_mode::invalid(-1);
const cull_mode cull_mode::none(0);
const cull_mode cull_mode::front(1);
const cull_mode cull_mode::back(2);
const cull_mode cull_mode::max(3);
