/**************************
NEVER CHANGE THIS FILE MANUALLY!

This File Was Generated By enums_gen.py Automatically.
************************/

#include "../../include/enums/fill_mode.h"

#include "eflib/include/eflib.h"

#ifdef _DEBUG
std::set<int>& fill_mode::get_fill_mode_table()
{
	static std::set<int> ret;
	return ret;
}
#endif

fill_mode::fill_mode(int v):val(v)
{
#ifdef _DEBUG
	if(get_fill_mode_table().find(v) != get_fill_mode_table().end()) {
		custom_assert(false, "");
	} else {
		get_fill_mode_table().insert(v);
	}
#endif
}

fill_mode fill_mode::cast(int val)
{
	#ifdef _DEBUG
	if(get_fill_mode_table().find(val) == get_fill_mode_table().end()){
		custom_assert(false, "");
		return fill_mode(0);
	}
	#endif
	return fill_mode(val);
}

const fill_mode fill_mode::invalid(-1);
const fill_mode fill_mode::wireframe(0);
const fill_mode fill_mode::solid(1);
const fill_mode fill_mode::max(2);
