/**************************
NEVER CHANGE THIS FILE MANUALLY!

This File Was Generated By enums_gen.py Automatically.
************************/

#include "../../include/enums/filter_type.h"

#include "eflib/include/eflib.h"

#ifdef _DEBUG
std::set<int>& filter_type::get_filter_type_table()
{
	static std::set<int> ret;
	return ret;
}
#endif

filter_type::filter_type(int v):val(v)
{
#ifdef _DEBUG
	if(get_filter_type_table().find(v) != get_filter_type_table().end()) {
		custom_assert(false, "");
	} else {
		get_filter_type_table().insert(v);
	}
#endif
}

filter_type filter_type::cast(int val)
{
	#ifdef _DEBUG
	if(get_filter_type_table().find(val) == get_filter_type_table().end()){
		custom_assert(false, "");
		return filter_type(0);
	}
	#endif
	return filter_type(val);
}

const filter_type filter_type::invalid(-1);
const filter_type filter_type::none(0);
const filter_type filter_type::point(1);
const filter_type filter_type::linear(2);
const filter_type filter_type::max(3);
