/**************************
NEVER CHANGE THIS FILE MANUALLY!

This File Was Generated By enums_gen.py Automatically.
************************/

#include "../../include/enums/index_type.h"

#include "eflib/include/eflib.h"

#ifdef _DEBUG
std::set<int>& index_type::get_index_type_table()
{
	static std::set<int> ret;
	return ret;
}
#endif

index_type::index_type(int v):val(v)
{
#ifdef _DEBUG
	if(get_index_type_table().find(v) != get_index_type_table().end()) {
		custom_assert(false, "");
	} else {
		get_index_type_table().insert(v);
	}
#endif
}

index_type index_type::cast(int val)
{
	#ifdef _DEBUG
	if(get_index_type_table().find(val) == get_index_type_table().end()){
		custom_assert(false, "");
		return index_type(0);
	}
	#endif
	return index_type(val);
}

const index_type index_type::invalid(-1);
const index_type index_type::uint16(0);
const index_type index_type::uint32(1);
const index_type index_type::max(2);
