/**************************
NEVER CHANGE THIS FILE MANUALLY!

This File Was Generated By enums_gen.py Automatically.
************************/

#include "../../include/enums/input_register_usage.h"

#include "eflib/include/eflib.h"

#ifdef _DEBUG
std::set<int>& input_register_usage::get_input_register_usage_table()
{
	static std::set<int> ret;
	return ret;
}
#endif

input_register_usage::input_register_usage(int v):val(v)
{
#ifdef _DEBUG
	if(get_input_register_usage_table().find(v) != get_input_register_usage_table().end()) {
		custom_assert(false, "");
	} else {
		get_input_register_usage_table().insert(v);
	}
#endif
}

input_register_usage input_register_usage::cast(int val)
{
	#ifdef _DEBUG
	if(get_input_register_usage_table().find(val) == get_input_register_usage_table().end()){
		custom_assert(false, "");
		return input_register_usage(0);
	}
	#endif
	return input_register_usage(val);
}

const input_register_usage input_register_usage::invalid(-1);
const input_register_usage input_register_usage::position(0);
const input_register_usage input_register_usage::attribute(1);
const input_register_usage input_register_usage::max(2);
