/**************************
NEVER CHANGE THIS FILE MANUALLY!

This File Was Generated By enums_gen.py Automatically.
************************/

#include "../../include/enums/lock_mode.h"

#include "eflib/include/eflib.h"

#ifdef _DEBUG
std::set<int>& lock_mode::get_lock_mode_table()
{
	static std::set<int> ret;
	return ret;
}
#endif

lock_mode::lock_mode(int v):val(v)
{
#ifdef _DEBUG
	if(get_lock_mode_table().find(v) != get_lock_mode_table().end()) {
		custom_assert(false, "");
	} else {
		get_lock_mode_table().insert(v);
	}
#endif
}

lock_mode lock_mode::cast(int val)
{
	#ifdef _DEBUG
	if(get_lock_mode_table().find(val) == get_lock_mode_table().end()){
		custom_assert(false, "");
		return lock_mode(0);
	}
	#endif
	return lock_mode(val);
}

const lock_mode lock_mode::invalid(-1);
const lock_mode lock_mode::read_only(0);
const lock_mode lock_mode::write_only(1);
const lock_mode lock_mode::read_write(2);
const lock_mode lock_mode::max(3);
