/**************************
NEVER CHANGE THIS FILE MANUALLY!

This File Was Generated By enums_gen.py Automatically.
************************/

#include "../../include/enums/render_target.h"

#include "eflib/include/eflib.h"

#ifdef _DEBUG
std::set<int>& render_target::get_render_target_table()
{
	static std::set<int> ret;
	return ret;
}
#endif

render_target::render_target(int v):val(v)
{
#ifdef _DEBUG
	if(get_render_target_table().find(v) != get_render_target_table().end()) {
		custom_assert(false, "");
	} else {
		get_render_target_table().insert(v);
	}
#endif
}

render_target render_target::cast(int val)
{
	#ifdef _DEBUG
	if(get_render_target_table().find(val) == get_render_target_table().end()){
		custom_assert(false, "");
		return render_target(0);
	}
	#endif
	return render_target(val);
}

const render_target render_target::invalid(-1);
const render_target render_target::color(0);
const render_target render_target::depth(1);
const render_target render_target::stencil(2);
const render_target render_target::max(3);
