/**************************
NEVER CHANGE THIS FILE MANUALLY!

This File Was Generated By enums_gen.py Automatically.
************************/

#include "../../include/enums/sampler_axis.h"

#include "eflib/include/eflib.h"

#ifdef _DEBUG
std::set<int>& sampler_axis::get_sampler_axis_table()
{
	static std::set<int> ret;
	return ret;
}
#endif

sampler_axis::sampler_axis(int v):val(v)
{
#ifdef _DEBUG
	if(get_sampler_axis_table().find(v) != get_sampler_axis_table().end()) {
		custom_assert(false, "");
	} else {
		get_sampler_axis_table().insert(v);
	}
#endif
}

sampler_axis sampler_axis::cast(int val)
{
	#ifdef _DEBUG
	if(get_sampler_axis_table().find(val) == get_sampler_axis_table().end()){
		custom_assert(false, "");
		return sampler_axis(0);
	}
	#endif
	return sampler_axis(val);
}

const sampler_axis sampler_axis::invalid(-1);
const sampler_axis sampler_axis::u(0);
const sampler_axis sampler_axis::v(1);
const sampler_axis sampler_axis::w(2);
const sampler_axis sampler_axis::max(3);
