/**************************
NEVER CHANGE THIS FILE MANUALLY!

This File Was Generated By enums_gen.py Automatically.
************************/

#include "../../include/enums/sampler_state.h"

#include "eflib/include/eflib.h"

#ifdef _DEBUG
std::set<int>& sampler_state::get_sampler_state_table()
{
	static std::set<int> ret;
	return ret;
}
#endif

sampler_state::sampler_state(int v):val(v)
{
#ifdef _DEBUG
	if(get_sampler_state_table().find(v) != get_sampler_state_table().end()) {
		custom_assert(false, "");
	} else {
		get_sampler_state_table().insert(v);
	}
#endif
}

sampler_state sampler_state::cast(int val)
{
	#ifdef _DEBUG
	if(get_sampler_state_table().find(val) == get_sampler_state_table().end()){
		custom_assert(false, "");
		return sampler_state(0);
	}
	#endif
	return sampler_state(val);
}

const sampler_state sampler_state::invalid(-1);
const sampler_state sampler_state::min(0);
const sampler_state sampler_state::mag(1);
const sampler_state sampler_state::mip(2);
const sampler_state sampler_state::max(3);
