/**************************
NEVER CHANGE THIS FILE MANUALLY!

This File Was Generated By enums_gen.py Automatically.
************************/

#ifndef SOFTART_ENUMS_ADDRESS_MODE_H
#define SOFTART_ENUMS_ADDRESS_MODE_H

#ifdef _DEBUG
#include <set>
#endif

class address_mode{

#ifdef _DEBUG
	static std::set<int>& get_address_mode_table();
#endif
	int val;
	explicit address_mode(int v);
	
public:
	static address_mode cast(int val);
	
	address_mode(const address_mode& rhs):val(rhs.val){}
	
	address_mode& operator =(const address_mode& rhs){ val=rhs.val; }
	
	operator int(){ return val; }
	
	friend inline bool operator == (const address_mode& lhs, const address_mode& rhs)
	{ return lhs.val == rhs.val; }
	
	friend inline bool operator != (const address_mode& lhs, const address_mode& rhs)
	{ return lhs.val != rhs.val; }
	
	static const address_mode invalid;
	static const address_mode wrap;
	static const address_mode mirror;
	static const address_mode clamp;
	static const address_mode border;
	static const address_mode max;
};

template<class T> T enum_cast(int val);

template<> inline address_mode enum_cast<address_mode>(int val){
	return address_mode::cast(val);
}

#endif