/**************************
NEVER CHANGE THIS FILE MANUALLY!

This File Was Generated By enums_gen.py Automatically.
************************/

#ifndef SOFTART_ENUMS_CULL_MODE_H
#define SOFTART_ENUMS_CULL_MODE_H

#ifdef _DEBUG
#include <set>
#endif

class cull_mode{

#ifdef _DEBUG
	static std::set<int>& get_cull_mode_table();
#endif
	int val;
	explicit cull_mode(int v);
	
public:
	static cull_mode cast(int val);
	
	cull_mode(const cull_mode& rhs):val(rhs.val){}
	
	cull_mode& operator =(const cull_mode& rhs){ val=rhs.val; }
	
	operator int(){ return val; }
	
	friend inline bool operator == (const cull_mode& lhs, const cull_mode& rhs)
	{ return lhs.val == rhs.val; }
	
	friend inline bool operator != (const cull_mode& lhs, const cull_mode& rhs)
	{ return lhs.val != rhs.val; }
	
	static const cull_mode invalid;
	static const cull_mode none;
	static const cull_mode front;
	static const cull_mode back;
	static const cull_mode max;
};

template<class T> T enum_cast(int val);

template<> inline cull_mode enum_cast<cull_mode>(int val){
	return cull_mode::cast(val);
}

#endif