/**************************
NEVER CHANGE THIS FILE MANUALLY!

This File Was Generated By enums_gen.py Automatically.
************************/

#ifndef SOFTART_ENUMS_FILL_MODE_H
#define SOFTART_ENUMS_FILL_MODE_H

#ifdef _DEBUG
#include <set>
#endif

class fill_mode{

#ifdef _DEBUG
	static std::set<int>& get_fill_mode_table();
#endif
	int val;
	explicit fill_mode(int v);
	
public:
	static fill_mode cast(int val);
	
	fill_mode(const fill_mode& rhs):val(rhs.val){}
	
	fill_mode& operator =(const fill_mode& rhs){ val=rhs.val; }
	
	operator int(){ return val; }
	
	friend inline bool operator == (const fill_mode& lhs, const fill_mode& rhs)
	{ return lhs.val == rhs.val; }
	
	friend inline bool operator != (const fill_mode& lhs, const fill_mode& rhs)
	{ return lhs.val != rhs.val; }
	
	static const fill_mode invalid;
	static const fill_mode wireframe;
	static const fill_mode solid;
	static const fill_mode max;
};

template<class T> T enum_cast(int val);

template<> inline fill_mode enum_cast<fill_mode>(int val){
	return fill_mode::cast(val);
}

#endif