/**************************
NEVER CHANGE THIS FILE MANUALLY!

This File Was Generated By enums_gen.py Automatically.
************************/

#ifndef SOFTART_ENUMS_FILTER_TYPE_H
#define SOFTART_ENUMS_FILTER_TYPE_H

#ifdef _DEBUG
#include <set>
#endif

class filter_type{

#ifdef _DEBUG
	static std::set<int>& get_filter_type_table();
#endif
	int val;
	explicit filter_type(int v);
	
public:
	static filter_type cast(int val);
	
	filter_type(const filter_type& rhs):val(rhs.val){}
	
	filter_type& operator =(const filter_type& rhs){ val=rhs.val; }
	
	operator int(){ return val; }
	
	friend inline bool operator == (const filter_type& lhs, const filter_type& rhs)
	{ return lhs.val == rhs.val; }
	
	friend inline bool operator != (const filter_type& lhs, const filter_type& rhs)
	{ return lhs.val != rhs.val; }
	
	static const filter_type invalid;
	static const filter_type none;
	static const filter_type point;
	static const filter_type linear;
	static const filter_type max;
};

template<class T> T enum_cast(int val);

template<> inline filter_type enum_cast<filter_type>(int val){
	return filter_type::cast(val);
}

#endif