#ifndef SASL_SEMANTIC_ANALYSER_SEMANTIC_ANALYSER_FORWARD_H
#define SASL_SEMANTIC_ANALYSER_SEMANTIC_ANALYSER_FORWARD_H

#define BEGIN_NS_SASL_SEMANTIC_ANALYSER() namespace sasl { namespace semantic_analyser{
#define END_NS_SASL_SEMANTIC_ANALYSER() } }

#endif