import sys
import os.path
def get_autogen_file_desc():
	ret =\
"""/**************************
NEVER CHANGE THIS FILE MANUALLY!

This File Was Generated By %s Automatically.
************************/

""" % os.path.split(sys.argv[0])[1]
	return ret