#ifndef SASL_VM_OP_CODE_DISPATCHER_H
#define SASL_VM_OP_CODE_DISPATCHER_H

#define SASL_DISPATCH_INSTRUCTION( INSTRUCTION, ARG0, ARG1 )	\
	case SASL_IFN( INSTRUCTION ):					\
	{												\
		SASL_ISN( INSTRUCTION ) (					\
			SASL_TYPED_INSTRUCTION(INSTRUCTION),	\
			ARG0, ARG1								\
			);										\
		break;										\
	}

#define SASL_DISPATCH_INSTRUCTIONS( INSTRUCTIONS, ARG0, ARG1 )	\
	BOOST_PP_SEQ_FOR_EACH( SASL_DISPATCH_INSTRUCTIONS_I, (ARG0, ARG1), INSTRUCTIONS )

#define SASL_DISPATCH_INSTRUCTIONS_I( r, data, elem )	\
	SASL_DISPATCH_INSTRUCTION( elem, BOOST_PP_TUPLE_REM(2) data )

#define 