set ( SALVIA_HOME_DIR "${CMAKE_HOME_DIRECTORY}" )
set ( SASL_HOME_DIR	"${CMAKE_HOME_DIRECTORY}" )

set( SALVIA_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_HOME_DIRECTORY}/bin/${SALVIA_PLATFORM_NAME}" )
set( SALVIA_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_HOME_DIRECTORY}/lib/${SALVIA_PLATFORM_NAME}" )

################ configurate 3rd party library paths ###############
set( SALVIA_3RD_PARTY_PATH "${SALVIA_HOME_DIR}/../3rd_party/" )
	
################ set llvm path ################
set( SALVIA_LLVM_PATH "${SALVIA_3RD_PARTY_PATH}/llvm/" )
set( SALVIA_LLVM_INCLUDE_PATH
	"${SALVIA_LLVM_PATH}/include/" "${SALVIA_LLVM_PATH}/config/${SALVIA_ENV_WITHOUT_BUILD_TYPE}/"
	)
set( SALVIA_LLVM_LIB_PATH "${SALVIA_LLVM_PATH}/lib/${SALVIA_ENVIRONMENT_NAME}" )