set ( SALVIA_HOME_DIR "${CMAKE_HOME_DIRECTORY}" )
set ( SASL_HOME_DIR	"${CMAKE_HOME_DIRECTORY}" )

set(SALVIA_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_HOME_DIRECTORY}/bin/${CMAKE_INFO_ENV_WITHOUT_BUILD_TYPE}")
set(SALVIA_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_HOME_DIRECTORY}/lib/${CMAKE_INFO_ENV_WITHOUT_BUILD_TYPE}")

if(NOT MSVC)
	set(SALVIA_RUNTIME_OUTPUT_DIRECTORY "${SALVIA_RUNTIME_OUTPUT_DIRECTORY}/${CMAKE_INFO_BUILD_TYPE}")
	set(SALVIA_LIBRARY_OUTPUT_DIRECTORY "${SALVIA_LIBRARY_OUTPUT_DIRECTORY}/${CMAKE_INFO_BUILD_TYPE}")
endif(NOT MSVC)

MESSAGE(STATUS "Runtime directory: ${SALVIA_RUNTIME_OUTPUT_DIRECTORY}")
MESSAGE(STATUS "Library directory: ${SALVIA_LIBRARY_OUTPUT_DIRECTORY}")
# Third-party
set( SALVIA_THIRD_PARTY_DIR "${SALVIA_HOME_DIR}/3rd_party/")

# THEAD POOL
set( SALVIA_THREAD_POOL_INCLUDE_DIR "${SALVIA_THIRD_PARTY_DIR}/threadpool" )
 
# LLVM
set( SALVIA_LLVM_INCLUDE_DIR "${SALVIA_LLVM_INSTALL_DIR}/include/")
set( SALVIA_LLVM_LIB_DIR "${SALVIA_LLVM_INSTALL_DIR}/lib" )

# FREETYPE
set( SALVIA_FREETYPE_INCLUDE_DIR "${SALVIA_THIRD_PARTY_DIR}/freetype2/include/")
set( SALVIA_FREETYPE_LIB_DIR "${SALVIA_FREETYPE_DIR}")

# FREEIMAGE
set( SALVIA_FREEIMAGE_INCLUDE_DIR "${SALVIA_FREEIMAGE_DIR}/Dist")
set( SALVIA_FREEIMAGE_LIB_DIR "${SALVIA_FREEIMAGE_DIR}/Dist")
