set ( SALVIA_HOME_DIR "${CMAKE_HOME_DIRECTORY}" )
set ( SASL_HOME_DIR	"${CMAKE_HOME_DIRECTORY}" )

set( SALVIA_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_HOME_DIRECTORY}/bin/${CMAKE_INFO_ENV_WITHOUT_BUILD_TYPE}" )
set( SALVIA_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_HOME_DIRECTORY}/lib/${CMAKE_INFO_ENV_WITHOUT_BUILD_TYPE}" )

# Third-party
set( SALVIA_THIRD_PARTY_DIR "${SALVIA_HOME_DIR}/3rd_party/")

# THEAD POOL
set( SALVIA_THREAD_POOL_INCLUDE_DIR "${SALVIA_THIRD_PARTY_DIR}/threadpool"

# WTL
set( SALVIA_WTL_INCLUDE_DIR ${SALVIA_3RD_PARTY_DIR}/wtl/include )  
 
# LLVM
set( SALVIA_LLVM_INCLUDE_DIR "${SALVIA_LLVM_INSTALL_DIR}/include/")
set( SALVIA_LLVM_LIB_DIR "${SALVIA_LLVM_INSTALL_DIR}/lib" )

# FREETYPE
set( SALVIA_FREETYPE_INCLUDE_DIR "${SALVIA_FREETYPE_DIR}/include/")
set( SALVIA_FREEIMAGE_LIB_DIR "${SALVIA_FREEIMAGE_DIR}")

# FREEIMAGE
set( SALVIA_FREEIMAGE_INCLUDE_DIR "${SALVIA_FREEIMAGE_DIR}")
set( SALVIA_FREEIMAGE_LIB_DIR "${SALVIA_FREEIMAGE_DIR}")