# set compile flags for MSVC

set(CMAKE_C_CXX_COMMON_FLAGS "${SALVIA_GCC_GCOV_PARAM} -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -w -fexceptions -msse2")
if(MINGW)
set(CMAKE_C_CXX_COMMON_FLAGS "${CMAKE_C_CXX_COMMON_FLAGS} -DWIN32 -DWINDOWS")
endif(MINGW)

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${CMAKE_C_CXX_COMMON_FLAGS}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CMAKE_C_CXX_COMMON_FLAGS} -std=c++11")

if (MINGW)
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -U__STRICT_ANSI__ -U__NO_ISOCEXT")
endif (MINGW)

set(CMAKE_C_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -D_DEBUG -g -O0")
set(CMAKE_C_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -DNDEBUG -O2" )
set(CMAKE_C_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELWITHDEBINFO} -DNDEBUG -g -O2")
set(CMAKE_C_FLAGS_MINSIZEREL "${CMAKE_CXX_FLAGS_MINSIZEREL} -DNDEBUG -Os")
