# Set compiling flags for MSVC

if(MSVC_VERSION LESS 1600)
	MESSAGE(FATAL_ERROR "Cannot support Microsoft Visual C++ version ${MSVC_VERSION}. Build will be stopped." )
endif()

set(CMAKE_CXX_FLAGS "/DWIN32 /D_WINDOWS /W4 /wd4503 /EHsc /GR") #C4503: decorated name length exceeded, name was truncated
set(CMAKE_C_FLAGS ${CMAKE_CXX_FLAGS})

if(SALVIA_PLATFORM_BITNESS EQUAL 32)
	set(CMAKE_CXX_FLAGS_DEBUG "/ZI")
	set(CMAKE_CXX_FLAGS_RELEASE "/arch:SSE")
	set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "/arch:SSE /Zi")
	set(CMAKE_CXX_FLAGS_MINSIZEREL "/arch:SSE")
else()
	set(CMAKE_CXX_FLAGS_DEBUG "/Zi")
	set(CMAKE_CXX_FLAGS_RELEASE "")
	set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "/Zi")
	set(CMAKE_CXX_FLAGS_MINSIZEREL "")
endif()

set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} /Od /Ob0 /RTC1 /MDd /GS /fp:precise /D_DEBUG")
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /O2 /Ob2 /GS- /fp:fast /MD /DNDEBUG")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELWITHDEBINFO} /O2 /Ob2 /GS- /fp:fast /MD /DNDEBUG")
set(CMAKE_CXX_FLAGS_MINSIZEREL "${CMAKE_CXX_FLAGS_MINSIZEREL} /O1 /Ob1 /GS- /fp:fast /MD /DNDEBUG")

set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /MP")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELWITHDEBINFO} /MP")
set(CMAKE_CXX_FLAGS_MINSIZEREL "${CMAKE_CXX_FLAGS_MINSIZEREL} /MP")

set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /GL")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELWITHDEBINFO} /GL")
set(CMAKE_CXX_FLAGS_MINSIZEREL "${CMAKE_CXX_FLAGS_MINSIZEREL} /GL")

set(CMAKE_C_FLAGS_DEBUG ${CMAKE_CXX_FLAGS_DEBUG})
set(CMAKE_C_FLAGS_RELEASE ${CMAKE_CXX_FLAGS_RELEASE})
set(CMAKE_C_FLAGS_RELWITHDEBINFO ${CMAKE_CXX_FLAGS_RELWITHDEBINFO})
set(CMAKE_C_FLAGS_MINSIZEREL ${CMAKE_CXX_FLAGS_MINSIZEREL})

foreach(flag_var
	CMAKE_EXE_LINKER_FLAGS CMAKE_MODULE_LINKER_FLAGS CMAKE_SHARED_LINKER_FLAGS)
	set(${flag_var} "")
endforeach(flag_var)
foreach(flag_var
	CMAKE_EXE_LINKER_FLAGS_DEBUG CMAKE_MODULE_LINKER_FLAGS_DEBUG CMAKE_SHARED_LINKER_FLAGS_DEBUG)
	set(${flag_var} "/INCREMENTAL /DEBUG")
endforeach(flag_var)
foreach(flag_var
	CMAKE_EXE_LINKER_FLAGS_RELEASE CMAKE_MODULE_LINKER_FLAGS_RELEASE CMAKE_SHARED_LINKER_FLAGS_RELEASE)
	set(${flag_var} "/INCREMENTAL:NO /OPT:REF /OPT:ICF")
endforeach(flag_var)
foreach(flag_var
	CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO)
	set(${flag_var} "/INCREMENTAL:NO /DEBUG /OPT:REF /OPT:ICF")
endforeach(flag_var)
foreach(flag_var
	CMAKE_EXE_LINKER_FLAGS_MINSIZEREL CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL)
	set(${flag_var} "/INCREMENTAL:NO /OPT:REF /OPT:ICF")
endforeach(flag_var)

foreach(flag_var
	CMAKE_EXE_LINKER_FLAGS_RELEASE CMAKE_MODULE_LINKER_FLAGS_RELEASE CMAKE_SHARED_LINKER_FLAGS_RELEASE)
	set(${flag_var} "${${flag_var}} /LTCG")
endforeach(flag_var)
foreach(flag_var
	CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO)
	set(${flag_var} "${${flag_var}} /LTCG")
endforeach(flag_var)
foreach(flag_var
	CMAKE_EXE_LINKER_FLAGS_MINSIZEREL CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL)
	set(${flag_var} "${${flag_var}} /LTCG")
endforeach(flag_var)