if(MSVC)
set( CMAKE_INFO_BUILD_TYPE "$(ConfigurationName)" )
endif(MSVC)

if(MINGW)
	set( CMAKE_INFO_BUILD_TYPE ${CMAKE_BUILD_TYPE} )
	string( TOLOWER ${CMAKE_INFO_BUILD_TYPE} CMAKE_INFO_BUILD_TYPE_LOWERCASE )
endif(MINGW)

set( CMAKE_INFO_ENV_WITHOUT_BUILD_TYPE "${CMAKE_INFO_PLATFORM_NAME}_${CMAKE_INFO_COMPILER_SHOWNAME}" )
set( CMAKE_INFO_ENVIRONMENT_NAME "${CMAKE_INFO_ENV_WITHOUT_BUILD_TYPE}_${CMAKE_INFO_BUILD_TYPE}")
