if( MSVC )
set( SALVIA_BUILD_TYPE "$(ConfigurationName)" )
endif()

if( MINGW )
	set( SALVIA_BUILD_TYPE ${CMAKE_BUILD_TYPE} )
	string( TOLOWER ${SALVIA_BUILD_TYPE} SALVIA_BUILD_TYPE_LOWERCASE )
endif()

set( SALVIA_ENV_WITHOUT_BUILD_TYPE "${SALVIA_PLATFORM_NAME}_${SALVIA_COMPILER_SHOWNAME}" )
set( SALVIA_ENVIRONMENT_NAME "${SALVIA_ENV_WITHOUT_BUILD_TYPE}_${SALVIA_BUILD_TYPE}")
