#ifndef SALVIAXRESOURCE_FORWARD_H
#define SALVIAXRESOURCE_FORWARD_H

#define BEGIN_NS_SALVIAXRESOURCE() namespace softartx{ namespace resource{
#define END_NS_SALVIAXRESOURCE() }}

#endif //SALVIAXRESOURCE_FORWARD_H